{
	//使用属性文件，配置生成器项目
	propConfig:{
		type:"org.nutz.ioc.impl.PropertiesProxy",
		fields:{
			paths:"code-generator/properties/code-generator.properties"
		}
	},
	//使用属性文件，配置WEB项目
	webPropConfig:{
		type:"org.nutz.ioc.impl.PropertiesProxy",
		fields:{
			paths:"code-generator/properties/code-web.properties"
		}
	}
}